DB_NAME = 'CarShowroom'
TABLE_NAME = "car_specs"

# Define table column types
col_types = {
    'vin': 'TEXT PRIMARY KEY',
    'back_legroom': 'REAL',
    'body_type': 'TEXT',
    'city': 'TEXT',
    'city_fuel_economy': 'REAL',
    'daysonmarket': 'INTEGER',
    'description': 'TEXT',
    'engine_cylinders': 'TEXT',
    'engine_displacement': 'REAL',
    'engine_type': 'TEXT',
    'exterior_color': 'TEXT',
    'franchise_dealer': 'TEXT',
    'franchise_make': 'TEXT',
    'front_legroom': 'REAL',
    'fuel_tank_volume': 'REAL',
    'fuel_type': 'TEXT',
    'has_accidents': 'TEXT',
    'height': 'REAL',
    'highway_fuel_economy': 'REAL',
    'horsepower': 'TEXT',
    'interior_color': 'TEXT',
    'is_new': 'TEXT',
    'latitude': 'REAL',
    'length': 'REAL',
    'listed_date': 'TEXT',
    'listing_color': 'TEXT',
    'listing_id': 'INTEGER',
    'longitude': 'REAL',
    'main_picture_url': 'TEXT',
    'major_options': 'TEXT',
    'make_name': 'TEXT',
    'maximum_seating': 'TEXT',
    'mileage': 'REAL',
    'model_name': 'TEXT',
    'owner_count': 'REAL',
    'power': 'TEXT',
    'price': 'REAL',
    'seller_rating': 'REAL',
    'sp_id': 'INTEGER',
    'sp_name': 'TEXT',
    'torque': 'TEXT',
    'transmission': 'TEXT',
    'transmission_display': 'TEXT',
    'trim_name': 'TEXT',
    'wheel_system': 'TEXT',
    'wheel_system_display': 'TEXT',
    'wheelbase': 'REAL',
    'width': 'REAL',
    'year': 'INTEGER'
}
